# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - azrickdaymanfunction

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'azrickdaymanfunction'  # Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'            # Path to function app files (update if in subdirectory, e.g., './src')
  PYTHON_VERSION: '3.11'                         # Python version

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x ".git/*" ".github/*" ".vscode/*" "__pycache__/*" "*.pyc" "venv/*"
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_69F4FCA4968A48A5820DA391794C34D0 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
